# MolSysMT Introduction

## Installation

To install MolSysMT, since there is no "stable" version yet, you have to clone the main repository:

```
git clone git@github.com:uibcdf/MolSysMT.git
```

There are some dependencies you have to solve manually (I have to make a file):
numpy, networkx, parmed, mdtraj, nglview, json, os, urllib, pyunitwizard...

Now, with your conda environment activated, install molsysmt as a developing module:

```
python setup.py develop
```

You can now open python, ipython or jupyter to check if molsysmt is imported with out complains:

```
import molsysmt as msm
```

Now, if this happens without errors or warnings, run the NGLView patch to make this library compatible with MolSysMT (This has to be done just the first time):

```
from molsysmt.tools import nglview
nglview.adding_molsysmt()
```

## Tasks to do

In order to solve these tasks, make a copy of this notebook and work over the copy. Name your notebook as you wish, and push it to the main branch of the repository with the cells to do the following: 

- Load the pdb file '1NCR' -from the Protein Data Bank or locally- as a molsysmt.MolSys object.

In [3]:
import molsysmt as msm

In [4]:
molecular_system = msm.convert('pdb:1NCR', to_form='molsysmt.MolSys')

- Get the form of the new object.

In [5]:
msm.get_form(molecular_system)

'molsysmt.MolSys'

- Print out the information summary of the new object.

In [6]:
msm.info(molecular_system)

- Check if the system has hydrogen atoms. Why there is no hydrogen atoms?

In [7]:
msm.has_hydrogens(molecular_system)

False

- Remove atoms from water molecules and ions

In [8]:
molecular_system = msm.remove_solvent(molecular_system, water=True, ions=True)

- Print out the information summary about the molecules of the new object.

In [9]:
msm.info(molecular_system)

- Protonate (add hydrogens) at pH=7.4 to the molecular system.

In [10]:
molecular_system = msm.add_missing_hydrogens(molecular_system, pH=7.4)

- Get the number of hydrogen atoms added to the system.

In [15]:
msm.get(molecular_system, selection='atom_type=="H"', n_atoms=True)

6160

- Get the sequence of aminoacids (3 letters code) of the molecule with index 0.

In [16]:
seq = msm.convert(molecular_system, selection='molecule_index==0',
                  to_form='aminoacids3:seq')

In [17]:
print(seq)

aminoacids3:AsnProValGluArgTyrValAspGluValLeuAsnGluValLeuValValProAsnIleAsnGlnSerHisProThrThrSerAsnAlaAlaProValLeuAspAlaAlaGluThrGlyHisThrAsnLysIleGlnProGluAspThrIleGluThrArgTyrValGlnSerSerGlnThrLeuAspGluMetSerValGluSerPheLeuGlyArgSerGlyCysIleHisGluSerValLeuAspIleValAspAsnTyrAsnAspGlnSerPheThrLysTrpAsnIleAsnLeuGlnGluMetAlaGlnIleArgArgLysPheGluMetPheThrTyrAlaArgPheAspSerGluIleThrMetValProSerValAlaAlaLysAspGlyHisIleGlyHisIleValMetGlnTyrMetTyrValProProGlyAlaProIleProThrThrArgAspAspTyrAlaTrpGlnSerGlyThrAsnAlaSerValPheTrpGlnHisGlyGlnProPheProArgPheSerLeuProPheLeuSerIleAlaSerAlaTyrTyrMetPheTyrAspGlyTyrAspGlyAspThrTyrLysSerArgTyrGlyThrValValThrAsnAspMetGlyThrLeuCysSerArgIleValThrSerGluGlnLeuHisLysValLysValValThrArgIleTyrHisLysAlaLysHisThrLysAlaTrpCysProArgProProArgAlaValGlnTyrSerHisThrHisThrThrAsnTyrLysLeuSerSerGluValHisAsnAspValAlaIleArgProArgThrAsnLeuThrThrVal


- How many atoms with name "CA" has the molecular system?

In [18]:
msm.get(molecular_system, selection='atom_name=="CA"', n_atoms=True)

804

- Get the list of indices of the groups named "VAL".

In [19]:
msm.get(molecular_system, target='group', selection='group_name=="VAL"',
        group_indices=True)

array([  2,   6,   9, ..., 735, 749, 778])

In [20]:
msm.select(molecular_system, target='group', selection='group_name=="VAL"')

array([  2,   6,   9, ..., 735, 749, 778])

- Get the coordinates of the atoms with name "CA" from those groups named "VAL". 

In [21]:
msm.get(molecular_system, target='atom',
        selection='atom_name=="CA" and group_name=="VAL"', coordinates=True)

array([[[ 4.26989985,  1.37030005,  8.99569988],
        [ 4.51170015,  1.84549999,  9.37160015],
        [ 4.76350021,  1.84780002,  9.81900024],
        ...,
        [ 0.95050001,  5.34950018, 13.08479977],
        [ 2.86789989,  3.6099    , 11.92710018],
        [ 4.47480011,  0.4429    ,  8.99610043]]]) <Unit('nanometer')>

- Show the view of the entity named "W11".

In [23]:
msm.view(molecular_system, selection='entity_name=="W11"')

NGLWidget()

- Show the view of the whole system (water and ions were removed).

In [25]:
msm.view(molecular_system)

NGLWidget()

- Get the minimum distance between any atom of the small molecule named "W11" and any atom of the molecule with index 0. The same with the molecules indexed 1, and 2.

In [27]:
msm.minimum_distance(molecular_system, selection='entity_name=="W11"',
                    selection_2="molecule_index==0")

(array([[   9, 1493]]), array([0.23532121]) <Unit('nanometer')>)

In [28]:
msm.minimum_distance(molecular_system, selection='entity_name=="W11"',
                    selection_2="molecule_index==1")

(array([[  23, 4233]]), array([0.35593877]) <Unit('nanometer')>)

In [29]:
msm.minimum_distance(molecular_system, selection='entity_name=="W11"',
                    selection_2="molecule_index==2")

(array([[ 19, 329]]), array([1.05140182]) <Unit('nanometer')>)

- Get the distance matrix between the atoms of type "C" from the small molecule named "W11" and any atom named "CA" of molecule with index 0.

In [32]:
msm.distance(molecular_system, selection='atom_type=="C" and entity_name=="W11"',
            selection_2='atom_name=="CA" and molecule_index==0')

array([[[3.62420737, 3.34308701, 3.53019266, ..., 4.49909229,
         4.39697191, 4.1867437 ],
        [3.61924814, 3.34947131, 3.54271893, ..., 4.40703697,
         4.31493622, 4.10884915],
        [3.53406338, 3.24535885, 3.43195129, ..., 4.58161979,
         4.47625337, 4.25744706],
        ...,
        [3.81622047, 3.46548052, 3.60406075, ..., 5.40672759,
         5.24719612, 5.01143812],
        [3.89729517, 3.53864328, 3.66469726, ..., 5.56869783,
         5.39957392, 5.16088915],
        [3.97309048, 3.6106282 , 3.72564986, ..., 5.64857668,
         5.47156315, 5.23213311]]]) <Unit('nanometer')>

- Get all phi and psi dihedral angles of the molecule type peptide.

In [33]:
msm.ramachandran_angles(molecular_system, selection='molecule_type=="peptide"')

(array([[12067, 12069, 12071, 12073],
        [12073, 12079, 12081, 12083],
        [12083, 12096, 12098, 12100],
        ...,
        [12434, 12441, 12443, 12445],
        [12445, 12465, 12467, 12469],
        [12469, 12484, 12486, 12488]]),
 array([[12060, 12064, 12067, 12069],
        [12069, 12071, 12073, 12079],
        [12079, 12081, 12083, 12096],
        ...,
        [12430, 12432, 12434, 12441],
        [12441, 12443, 12445, 12465],
        [12465, 12467, 12469, 12484]]),
 array([[-135.65476665,  -97.51716098,  -63.55960412, ...,  -82.88016525,
          -92.46415849,   66.8792718 ]]) <Unit('degree')>,
 array([[ 73.43742576, 130.61779478,  72.27113957, ..., 167.33405557,
         162.94270463, 156.04392433]]) <Unit('degree')>)

- Get all covalent chains with the sequence of atoms with name "C1B"-"C2B"-"C3B"-"C4B"-"C5B"-"C6B"-"C1B"

In [35]:
msm.covalent_chains(molecular_system, chain=['atom_name=="C1B"', 'atom_name=="C2B"',
                    'atom_name=="C3B"', 'atom_name=="C4B"', 'atom_name=="C5B"',
                    'atom_name=="C6B"', 'atom_name=="C1B"',])

array([[12506, 12507, 12509, 12510, 12511, 12512, 12506]])

- Get all covalent chains with 7 atoms type "C". How many chains you got? Can this be a bug? If you think so, open and issue reporting this possible bug. Could the method `covalent_chains` be used to detect rings? Should we define a method to get covalent rings?

In [37]:
a = msm.covalent_chains(molecular_system, chain=['atom_type=="C"', 'atom_type=="C"',
                    'atom_type=="C"', 'atom_type=="C"', 'atom_name=="C"',
                    'atom_type=="C"', 'atom_type=="C"',])

In [38]:
len(a)

8632

In [39]:
a

array([[    6,     4,     6, ...,     6,     4,     6],
       [    6,     4,     6, ...,     6,     4,     8],
       [    6,     4,     8, ...,     6,     4,     6],
       ...,
       [12490, 12486, 12490, ..., 12488, 12486, 12490],
       [12490, 12493, 12490, ..., 12488, 12486, 12488],
       [12490, 12493, 12490, ..., 12488, 12486, 12490]])